server:
  port: '8080'

stat-service:
  url: 'http://localhost:9090'

spring:
    datasource:
      driverCLassName: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/ewm-db
      username: ewm
      password: ewm
    jpa:
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          format_sql: true
    sql:
      init:
        mode: always