CREATE TABLE IF NOT EXISTS users (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                VARCHAR(255) NOT NULL,
    email               VARCHAR(512) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS event_categories (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                VARCHAR(255) UNIQUE NOT NULL,
    CONSTRAINT pk_event_category PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilations (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pinned              BOOLEAN DEFAULT FALSE,
    title               VARCHAR(50) NOT NULL,
    CONSTRAINT pk_compilation PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS locations (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lat                 FLOAT8 NOT NULL,
    lon                 FLOAT8 NOT NULL,
    CONSTRAINT pk_location PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title               VARCHAR(255) NOT NULL,
    annotation          VARCHAR(2048) NOT NULL,
    description         VARCHAR(7000) NOT NULL,
    category_id         BIGINT REFERENCES event_categories(id),
    event_date          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    initiator_id        BIGINT REFERENCES users(id),
    location_id         BIGINT REFERENCES locations(id),
    created_on          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    published_on        TIMESTAMP WITHOUT TIME ZONE,
    paid                BOOLEAN DEFAULT FALSE,
    participant_limit   INTEGER DEFAULT 0,
    request_moderation  BOOLEAN DEFAULT TRUE,
    state               VARCHAR(50) DEFAULT 'PENDING',
    CONSTRAINT pk_event PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS event_requests (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id            BIGINT REFERENCES events(id),
    requester_id        BIGINT REFERENCES users(id),
    created             TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status              VARCHAR(20),
    CONSTRAINT pk_event_request PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilation_events (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    compilation_id      BIGINT REFERENCES compilations(id),
    event_id            BIGINT REFERENCES events(id),
    CONSTRAINT pk_compilation_event PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS event_comments (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id            BIGINT REFERENCES events(id),
    author_id           BIGINT REFERENCES users(id),
    created             TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    edited              TIMESTAMP WITHOUT TIME ZONE,
    deleted             BOOLEAN DEFAULT FALSE,
    text                VARCHAR(7000) NOT NULL,
    CONSTRAINT pk_event_comment PRIMARY KEY (id)
);