server:
  port: '9090'

spring:
  datasource:
    driverCLassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6541/stats-db
    username: stats
    password: stats
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always